openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'CHPQA Alpha Prototype API'
  description: CHPQA Schemes and Submissions Proxy/Facade API

paths:
  /schemes/{userId}:
    parameters:
      - name: userId
        description: The user id of the Responsible Person (RP)
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/UserId'
    get:
      summary: Read all schemes for the supplied userId
      responses:
        '200':
          description: The Scheme corresponding to the provided `SchemeId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scheme'
  /scheme/{ref}:
    parameters:
      - name: ref
        description: The identifier of the scheme
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/SchemeId'
    get:
      summary: Read a Scheme
      responses:
        '200':
          description: The Scheme corresponding to the provided `SchemeId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scheme'
        404:
          description: No Scheme found for the provided `SchemeId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /submission/{ref}:
    parameters:
      - name: ref
        description: The identifier of the scheme
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/SchemeId'
    post:
      summary: Create a submission
      responses:
        '201':
          description: The Scheme corresponding to the provided `SchemeId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Submission'
        404:
          description: No Scheme found for the provided `SchemeId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    UserId:
      description: The identifier of a Responsible Person (RP)
      type: string
    Ref:
      description: The identifier of a schema
      type: string
    Scheme:
      type: object
      required:
        - ref
        - name
        - sector
        - fuelBillFrequency
      properties:
        ref:
          $ref: '#/components/schemas/SchemeId'
        name:
          type: string
        sector:
          type: string
          enum:
            - Chemical industry
            - Commerce
            - Construction
            - Electrical and instrument engineering
            - Extraction, mining and agglomeration
            - Food, beverages and tobacco
            - Iron and steel
            - Mechanical engineering and metal products
            - Mineral products (eg glass, cement, bricks)
            - Non ferrous metals
            - Oil refineries
            - Other
            - Other industrial branches
            - Paper, publishing and printing
            - Power generation
            - Public Administration
            - Sewage treatment
            - Textiles, clothing and footwear
            - Transport
            - Vehicles
        fuelBillFrequency:
          type: string
          enum:
            - Monthly
            - Quarterly
            - Annually
            - Other
        totalPowerCapacity:
          type: number
        maximumHeatOutput:
          type: number
        totalPowerCapacityUnderMHC:
          type: number
    Submission:
      type: object
      required:
        - ref
        - submissionId
        - submittedBy
        - submittedDate
      properties:
        ref:
          $ref: '#/components/schemas/SchemeId'
        submissionId:
          type: string
        schemeId:
          type: string
        annualOperatingHours:
          type: number
        estimatedEnergyInputPrimeMover:
          type: number
        estimatedEnergyInputBoilers:
          type: number
        estimatedHeatOutputPrimeMover:
          type: number
        estimatedHeatOutputBoilers:
          type: number
        uncertaintyAdjustmentFactorFuel:
          type: number
        uncertaintyAdjustmentFactorHeat:
          type: number
        uncertaintyAdjustmentFactorPower:
          type: number
        uncertaintyAdjustmentFactorFilename:
          type: number
        powerEfficiancyPrecentage:
          type: number
        qualityIndexScore:
          type: number
        claimRenewableCertificate:
          type: boolean
        qualifyForContractsOfDifference:
          type: boolean
        claimSecretaryOfStateCertificate:
          type: boolean
        doesExportElectricity:
          type: boolean
        doesExportHeat:
          type: boolean
        heatExportCustomer:
          type: string
        claimClimateChangeLevyLastYear:
          type: boolean
        claimClimatePriceFloorExemptionLastYear:
          type: boolean
        designHeatRecoveryCapacity:
          type: number
        designPowerEfficiency:
          type: number
        otherInformation:
          type: string
        otherInformationFilename:
          type: string
        submittedBy:
          type: string
        submittedDate:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []