openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'CHPQA Alpha Prototype API'
  description: CHPQA Schemes and Submissions Proxy/Facade API

paths:
  /schemes/{userId}:
    parameters:
      - name: userId
        description: The user id of the Responsible Person (RP)
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/UserId'
    get:
      summary: Read all schemes for the supplied userId
      responses:
        '200':
          description: The Scheme corresponding to the provided `SchemeId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scheme'
  /scheme/{ref}:
    parameters:
      - name: ref
        description: The identifier of the scheme
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/schemeId'
    get:
      summary: Read a Scheme
      responses:
        '200':
          description: The Scheme corresponding to the provided `SchemeId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scheme'
        404:
          description: No Scheme found for the provided `SchemeId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /submission/{ref}:
    parameters:
      - name: ref
        description: The identifier of the scheme
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/schemeId'
    post:
      summary: Create a submission
      responses:
        '201':
          description: The Scheme corresponding to the provided `SchemeId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scheme'
        404:
          description: No Scheme found for the provided `SchemeId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    UserId:
      description: The identifier of a Responsible Person (RP)
      type: string
    schemeId:
      description: The identifier of a schema
      type: string
    scheme:
      type: object
      properties:
        info:
          type: object
          properties:
            ref:
              type: string
            name:
              type: string
          required:
            - ref
            - name
        details:
          type: object
          properties:
            sector:
              type: string
              enum:
                - Chemical industry
                - Commerce
                - Construction
                - Electrical and instrument engineering
                - Extraction, mining and agglomeration
                - Food, beverages and tobacco
                - Iron and steel
                - Mechanical engineering and metal products
                - Mineral products (eg glass, cement, bricks)
                - Non ferrous metals
                - Oil refineries
                - Other
                - Other industrial branches
                - Paper, publishing and printing
                - Power generation
                - Public Administration
                - Sewage treatment
                - Textiles, clothing and footwear
                - Transport
                - Vehicles
            fuelBillFrequency:
              type: string
              enum:
                - Monthly
                - Quarterly
                - Annually
                - Other            
            diagrams:
              type: array
              items:
                type: string
            primeMovers:
              type: array
              items:
                type: object
                properties:
                  tagNumber:
                    type: number
                  type:
                    type: string
                  fuel:
                    type: string
                  manufacturer:
                    type: string
                  model:
                    type: string
                  yearCommissioned:
                    type: number
                  maximumRatedHeat:
                    type: string
                  maximumRatedPower:
                    type: string
                required:
                  - tagNumber
                  - type
                  - fuel
                  - manufacturer
                  - model
                  - yearCommissioned
                  - maximumRatedHeat
                  - maximumRatedPower
            boilers:
              type: array
              items:
                type: object
                properties:
                  tagNumber:
                    type: number
                  type:
                    type: string
                  details:
                    type: string
                  manufacturer:
                    type: string
                  model:
                    type: string
                  yearCommissioned:
                    type: number
                  maximumRatedHeat:
                    type: string
                  maximumRatedPower:
                    type: string
                required:
                  - tagNumber
                  - type
                  - details
                  - manufacturer
                  - model
                  - yearCommissioned
                  - maximumRatedHeat
                  - maximumRatedPower
          required:
            - sector
            - fuelBillFrequency
            - diagrams
            - primeMovers
            - boilers
        meters:
          type: object
          properties:
            fuelMeters:
              type: array
              items:
                type: object
                properties:
                  tag:
                    type: string
                  diagramReferenceNumber:
                    type: string
                  yearInstalled:
                    type: number
                  outputsRange:
                    type: string
                  outputsUnit:
                    type: string
                  modelType:
                    type: string
                  uncertainty:
                    type: number
                  meterPointReference:
                    type: string
                  serialNumber:
                    type: string
                required:
                  - tag
                  - diagramReferenceNumber
                  - yearInstalled
                  - outputsRange
                  - outputsUnit
                  - modelType
                  - uncertainty
                  - serialNumber
            electricityMeters:
              type: array
              items:
                type: object
                properties:
                  tag:
                    type: string
                  diagramReferenceNumber:
                    type: string
                  yearInstalled:
                    type: number
                  outputsRange:
                    type: string
                  outputsUnit:
                    type: string
                  modelType:
                    type: string
                  uncertainty:
                    type: number
                  serialNumber:
                    type: string
                  meterPointReference:
                    type: string
                required:
                  - tag
                  - diagramReferenceNumber
                  - yearInstalled
                  - outputsRange
                  - outputsUnit
                  - modelType
                  - uncertainty
                  - serialNumber
            heatMeters:
              type: array
              items:
                type: object
                properties:
                  tag:
                    type: string
                  diagramReferenceNumber:
                    type: string
                  yearInstalled:
                    type: number
                  outputsRange:
                    type: string
                  outputsUnit:
                    type: string
                  modelType:
                    type: string
                  uncertainty:
                    type: number
                  serialNumber:
                    type: string
                  meterPointReference:
                    type: string
                required:
                  - tag
                  - diagramReferenceNumber
                  - yearInstalled
                  - outputsRange
                  - outputsUnit
                  - modelType
                  - uncertainty
                  - serialNumber
          required:
            - fuelMeters
            - electricityMeters
            - heatMeters
        additionalInformation:
          type: object
          properties:
            details:
              type: string
          required:
            - details
      required:
        - info
        - details
        - meters
        - additionalInformation
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []