:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\DESNZ.CHPQA.Alpha.Prototype
dotnet build src\DESNZ.CHPQA.Alpha.Prototype
echo Now, run the following to start the project: dotnet run -p src\DESNZ.CHPQA.Alpha.Prototype\DESNZ.CHPQA.Alpha.Prototype.csproj --launch-profile web.
echo.
