#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/DESNZ.CHPQA.Alpha.Prototype/ && \
    dotnet build src/DESNZ.CHPQA.Alpha.Prototype/ && \
    echo "Now, run the following to start the project: func start"
